# These are supported funding model platforms

github: ['official-antique'] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://buymeacoffee.com/antiquecodes', 'https://paypal.com/paypalme/officialantique', 'https://twitter.com/antique_codes'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
